#!/bin/bash

# Variables
USERNAME=$(whoami)
DATE=$(date +"%Y-%m-%d %H:%M:%S")
HOSTNAME=$(hostname)
OS=$(lsb_release -d | awk -F"\t" '{print $2}')
UPTIME=$(uptime -p)
CPU=$(lscpu | grep "Model name" | awk -F": " '{print $2}')
RAM=$(free -h | grep "Mem" | awk '{print $2}')
DISK=$(lsblk -d -o NAME,SIZE | grep -v "NAME")
VIDEO=$(lspci | grep -i vga | awk -F": " '{print $3}')
IP_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(systemd-resolve --status | grep "DNS Servers" | awk '{print $3}')
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
DISK_SPACE=$(df -h / | awk 'NR==2 {print $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average: ' '{print $2}')
MEMORY_ALLOCATION=$(free -h | grep "Mem" | awk '{print "Total: " $2 ", Used: " $3 ", Free: " $4}')
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | tr '\n' ',' | sed 's/,$//')

# Report
echo "System Report generated by $USERNAME, $DATE"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disks: $DISK"
echo "Video: $VIDEO"
echo ""
echo "Network Information"
echo "-------------------"
echo "IP Address: $IP_ADDRESS"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Memory Allocation: $MEMORY_ALLOCATION"
echo "Listening Network Ports: $LISTENING_PORTS"
